import {Component,signal} from '@angular/core';import {RouterLink} from '@angular/router';import {FormsModule,ReactiveFormsModule,FormControl,FormGroup,Validators} from '@angular/forms';
import {PageHeading,Feedback,Pagination} from '../../../../shared/ui/page';import {RfidPage} from '../../page-base';import {RfidNavComponent} from '../../shared/rfid-nav/rfid-nav.component';import {PendingRequestsComponent} from '../../shared/pending-requests/pending-requests.component';import * as M from '../../models';import {inject} from '@angular/core';import {RfidForm} from '../../form-base';import {ScanPickerComponent} from '../../selectors/scan-picker/scan-picker.component';import {toInstant,epc,uuidPattern} from '../../rules';
@Component({selector:'tc-rfid-command-plan',imports:[FormsModule,PageHeading,Feedback,RfidNavComponent,PendingRequestsComponent,ReactiveFormsModule,ScanPickerComponent],templateUrl:'./command-plan.component.html',styleUrl:'./command-plan.component.scss'})
export class CommandPlanComponent extends RfidForm {
 readonly form=this.fb.nonNullable.group({yardUuid:['',this.uuid],assetUuid:['',this.uuid],tagUuid:['',this.uuid],readerUuid:['',this.uuid],deviceUuid:['',this.uuid],type:['WRITE_EPC',Validators.required],expiresAt:['',Validators.required],utcOffset:['+00:00',[Validators.required,Validators.pattern(/^[+-]\d{2}:\d{2}$/)]]});
 readonly asset=signal<M.Asset|null>(null);readonly chip=signal<M.ProgrammingTag|null>(null);readonly epc=epc;
 ngOnInit(){this.form.patchValue({yardUuid:this.session.selectedYard(),assetUuid:this.route.snapshot.queryParamMap.get('assetUuid')??'',tagUuid:this.route.snapshot.queryParamMap.get('tagUuid')??''});this.form.markAsPristine();}
 override pick(key:string,value:string){super.pick(key,value);this.chip.set(null);if(key==='assetUuid')this.asset.set(null);if(key==='readerUuid')this.form.controls.deviceUuid.setValue('');if(key==='yardUuid')this.form.patchValue({readerUuid:'',deviceUuid:''});}
 async inspectSelection(){const v=this.form.getRawValue();if(!v.assetUuid||!v.tagUuid||!v.readerUuid){this.error.set('Selecciona equipo, lector y UUID del chip.');return;}
 await this.request(async()=>({asset:await this.get<M.Asset>('/assets/'+v.assetUuid+'/summary'),chip:await this.get<M.ProgrammingTag>('/programming-tags/'+v.tagUuid,{assetUuid:v.assetUuid,readerUuid:v.readerUuid})}),r=>{this.asset.set(r.asset);this.chip.set(r.chip);});}
 async save(){if(!this.validForm())return;const v=this.form.getRawValue();await this.mutate(async()=>{const asset=await this.get<M.Asset>('/assets/'+v.assetUuid+'/summary');if(!this.access.can('RFID_TAG_MANAGE',asset.identity.yardUuid)||!this.access.can('RFID_SCAN',v.yardUuid))throw new Error('Faltan capacidades sobre equipo o lector.');return this.pending.post<M.Command>('/commands',{assetUuid:v.assetUuid,tagUuid:v.tagUuid,readerUuid:v.readerUuid,deviceUuid:v.deviceUuid,type:v.type,expiresAt:this.expires()});},r=>{this.form.markAsPristine();void this.router.navigate(['/rfid/comandos',r.uuid]);});}
}
