import {Component,signal} from '@angular/core';import {RouterLink} from '@angular/router';import {FormsModule,ReactiveFormsModule,FormControl,FormGroup,Validators} from '@angular/forms';
import {PageHeading,Feedback,Pagination} from '../../../../shared/ui/page';import {RfidPage} from '../../page-base';import {RfidNavComponent} from '../../shared/rfid-nav/rfid-nav.component';import {PendingRequestsComponent} from '../../shared/pending-requests/pending-requests.component';import * as M from '../../models';import {inject} from '@angular/core';import {RfidForm} from '../../form-base';import {ScanPickerComponent} from '../../selectors/scan-picker/scan-picker.component';import {toInstant,epc,uuidPattern} from '../../rules';
@Component({selector:'tc-rfid-session-plan',imports:[FormsModule,PageHeading,Feedback,RfidNavComponent,PendingRequestsComponent,ReactiveFormsModule,ScanPickerComponent],templateUrl:'./session-plan.component.html',styleUrl:'./session-plan.component.scss'})
export class SessionPlanComponent extends RfidForm {
 readonly form=this.fb.nonNullable.group({yardUuid:['',this.uuid],readerUuid:['',this.uuid],deviceUuid:['',this.uuid],gateUuid:['',[Validators.pattern(uuidPattern)]],purpose:['IDENTIFY',Validators.required],expiresAt:['',Validators.required],utcOffset:['+00:00',[Validators.required,Validators.pattern(/^[+-]\d{2}:\d{2}$/)]]});
 ngOnInit(){this.form.patchValue({yardUuid:this.route.snapshot.queryParamMap.get('yardUuid')??this.session.selectedYard(),gateUuid:this.route.snapshot.queryParamMap.get('gateUuid')??'',purpose:this.route.snapshot.queryParamMap.get('purpose')??'IDENTIFY'});this.form.markAsPristine();}
 override pick(key:string,value:string){super.pick(key,value);if(key==='readerUuid')this.form.controls.deviceUuid.setValue('');if(key==='yardUuid'){this.form.patchValue({readerUuid:'',deviceUuid:'',gateUuid:''});}}
 async save(){if(!this.validForm())return;const v=this.form.getRawValue();if(!this.access.can('RFID_SCAN',v.yardUuid)){this.error.set('Sin permiso de escaneo para el patio.');return;}if(v.purpose==='GATE'&&!v.gateUuid){this.error.set('GATE exige seleccionar un portón y un lector fijo.');return;}
 await this.mutate(()=>this.pending.post<M.ScanSession>('/sessions',{readerUuid:v.readerUuid,deviceUuid:v.deviceUuid,yardUuid:v.yardUuid,gateUuid:v.purpose==='GATE'?v.gateUuid:null,purpose:v.purpose,expiresAt:this.expires()}),r=>{this.form.markAsPristine();void this.router.navigate(['/rfid/sesiones',r.uuid]);});}
}
